packages:
  - "apps/*"
  - "apps/*/test"
  - "apps/*/e2e"
  - "eslint-config"
allowBuilds:
  '@parcel/watcher': true
  '@prisma/engines': true
  '@scarf/scarf': false
  prisma: true
  unrs-resolver: false
