sonar.sourceEncoding=UTF-8

sonar.sources=apps/api/src,apps/web/src
sonar.tests=apps/api/src,apps/web/test
sonar.test.inclusions=apps/api/src/**/*.spec.ts,apps/web/test/**/*.test.ts,apps/web/test/**/*.test.tsx
sonar.exclusions=apps/api/src/generated/**,apps/web/src/components/ui/**

sonar.javascript.lcov.reportPaths=apps/web/test/coverage/lcov.info,apps/api/coverage/lcov.info
sonar.typescript.lcov.reportPaths=apps/web/test/coverage/lcov.info,apps/api/coverage/lcov.info
